In [3]:
import pandas as pd
import numpy as np

## Pandas

In [1]:
# Pandas is a lib that woks with dataframes
# A Dataframe is like an excel spreedsheet

# colums and rows
# In Pandas a column is a serie

# The columns name are called Features

In [ ]:
# How to create a dataframe
# Series are 1D array. are the columns
# To handle 1D arrays we use Numpy lib

In [ ]:
# How to create a Dataframe
# 1. Arrays
# 2. Dictionary
# 3. CSV File

### Option 1 using Array

In [5]:
# creating an array
data = np.array([[1,4], [2,5], [3,6]])

In [8]:
# creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns=['col1', 'col2'])

In [9]:
# showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

### Option 2 - create a Dataframe from a dictionary

In [10]:
# lists used for this example
states = ['Benguela', 'Navegantes', 'Lobito', 'Cubal']
population = [800030, 750000, 800000, 300008]

In [12]:
# Storing lists with a dictionary
dict_states = {'states': states, 'population': population}

In [15]:
# creating the dataframe
df_population = pd.DataFrame(dict_states)

In [16]:
# showing the databaframe
df_population

       states  population
0    Benguela      800030
1  Navegantes      750000
2      Lobito      800000
3       Cubal      300008